### ISSUE TITLE
Investigate Travis latest failures

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Website-Tests#132]
Travis has been [failing](https://travis-ci.org/IATI/IATI-Website-Tests/builds/500319721) for days now. We should investigate and action.

This is the stacktrace:

```self = <test_discuss.TestIATIDiscuss object at 0x7f144892b358>
loaded_request = <Response [200]>
    def test_contains_links(self, loaded_request):
        """
            Test that each page contains links to the defined URLs.
            """
        result = utility.get_links_from_page(loaded_request)
    
>       assert "http://iatistandard.org/en/about/" in result
E       AssertionError: assert 'http://iatistandard.org/en/about/' in ['/', '/c/community-zone', '/c/standard-management', '/c/events', '/c/consultations', '/c/notifications', ...]
tests/test_discuss.py:20: AssertionError
_______ TestIATIDiscuss.test_contains_links[IATI Discuss Welcome Thread] _______
self = <test_discuss.TestIATIDiscuss object at 0x7f1448939be0>
loaded_request = <Response [200]>
    def test_contains_links(self, loaded_request):
        """
            Test that each page contains links to the defined URLs.
            """
        result = utility.get_links_from_page(loaded_request)
    
>       assert "http://iatistandard.org/en/about/" in result
E       AssertionError: assert 'http://iatistandard.org/en/about/' in ['/', '/t/welcome-to-iati-discuss/6', '/u/system', 'http://discuss.iatistandard.org/categories', 'http://discuss.iatistandard.org/c/community-zone', 'http://discuss.iatistandard.org/c/standard-management', ...]```

**Comment by Ocre42** [comment]
As part of the reorganisation of IATI-Discuss, some things appear to have gone missing, including a link to the iatistandard.org website, which is why the tests are failing. While I could easily rewrite the tests around that, I think we should definitely have a link to the iatistandard.org website somewhere within discuss, the question being where should it live. 
There's also a couple inconsistencies with discuss across different users, most noticeably the pinned "Welcome to IATI Discuss" thread, which although unrelated to the failing tests, it should also be looked into.

**Comment by sargentfrancesca** [comment]
Great, thanks @Ocre42 .

What are the actions from here?

**Comment by samuele-mattiuzzo** [comment]
This is a good starting investigation @Ocre42 .

Have you investigated with Josh whether those items are missing on purpose or have been removed by mistake? Are they desperately needed? If not, can we not just remove the tests?

**Comment by Ocre42** [comment]
@samuele-mattiuzzo as mentioned, tests check links for the iatistandard website, with the makeover those links are now gone and there's currently no way to get to iatistandard.org from discuss. 
@sargentfrancesca I'd say the next stage is have a discussion with the team as to where this link should live.

**Comment by Ocre42** [comment]
@IATI/bas if you could have a look at this and let us know what the decision on the links to IATI websites, let us know here!

**Comment by Ocre42** [comment]
Layout now includes header with links to iatistandard.org, sorted.
