### ISSUE TITLE
Long request timeout

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Website-Tests#67]
When requests provide no data, Travis times out and does not continue.

For example: https://travis-ci.org/IATI/IATI-Website-Tests/builds/299494824

There should be a shorter request timeout so that if some requests hang, the tests continue so that it can be seen whether there are other failures with services checked later in the test process.

**Comment by andylolz** [comment]
`requests` doesn’t timeout by default. The docs recommend setting the `timeout` param in production code:
https://requests.readthedocs.io/en/master/user/advanced/#timeouts
